name: Build NixOS Images

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nixos:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - host: google
            runner: ubuntu-latest
            architecture: x86_64
            extension: raw.tar.gz
            image: nixosConfigurations.google.config.system.build.image
          - host: oci
            runner: ubuntu-24.04-arm
            architecture: aarch64
            extension: qcow2
            image: packages.aarch64-linux.oci-image
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - run: |
          test "$(uname -m)" = "${{ matrix.architecture }}"
          df -h / /nix/store
      - if: matrix.host == 'google'
        run: test -w /dev/kvm
      - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --no-link
      - run: nix build .#${{ matrix.image }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.host }}
          path: result/*.${{ matrix.extension }}
          if-no-files-found: error
